map_server:
    ros__parameters:
        yaml_filename:  "/home/ardu_ws/install/share/aimm_navigation/maps/E.yaml"
        topic_name:     "map"
        frame_id:       "map"
        use_sim_time:   false