navsat_transform_node:
  ros__parameters:
    gps_topic: /mavros/global_position/raw/fix
    gps_queue_size: 10

    imu_topic: /mavros/imu/data
    imu_queue_size: 10

    world_frame: map
    odom_frame: odom
    base_link_frame: base_link

    broadcast_utm_transform: true
    publish_filtered_gps: true

    wait_for_datum: false        # ← this is CRITICAL
    use_odometry_yaw: false      # or true if you're relying on /odom for yaw
