target_frame:       base_link
transform_tolerance: 0.01
min_height:         -0.1
max_height:         0.1
angle_min:          -3.1416
angle_max:          3.1416
angle_increment:    0.0043633    # ~0.25°
scan_time:          0.1
range_min:          0.5
range_max:          30.0
use_inf:            true
inf_epsilon:        1.0
