teleop:
  move:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: cmd_vel
    axis_mappings:
      - axis: 1
        target: linear.x  # Forward/backward movement
        scale: 1.0
      - axis: 3
        target: angular.z  # Rotate the thruster (yaw)
        scale: 1.0

  joy_priority:
    type: action
    action_name: joy_priority_action
    buttons: [9]

  # Control for rotating the single mid thruster around the Z-axis (yaw)
  rotate_mid_thruster:
    type: topic
    message_type: std_msgs/Float32
    topic_name: /lpv/thrusters/mid_thrust_angle
    axis_mappings:
      - axis: 3
        target: data
        scale: 1.0


